import { SupportedEngine } from "@common/enums/engine";

export const restrictedQueryOperations = {
  [SupportedEngine.POSTGRESQL]: [
    "pg_read_file",
    "pg_read_binary_file",
    "pg_ls_dir",
    "pg_stat_file",
    "lo_import",
    "lo_export",
    "create extension",
    "alter system",
    "create role",
    "alter role",
    "drop role",
    "create user",
    "alter user",
    "drop user",
    "create database",
    "alter database",
    "drop database",
    "grant ",
    "revoke ",
    "\\",
  ],
  [SupportedEngine.MONGODB]: [
    "db.admincommand",
    "db.system.",
    "db.dropdatabase",
    "db.createuser",
    "db.dropuser",
    "db.updateuser",
    "sleep(",
    "while(",
  ],
  [SupportedEngine.MYSQL]: [
    "load_file",
    "into outfile",
    "into dumpfile",
    "load data infile",
    "load data local infile",
    "install plugin",
    "uninstall plugin",
    "set global",
    "set persist",
    "create user",
    "alter user",
    "drop user",
    "create role",
    "drop role",
    "grant ",
    "revoke ",
    "\\",
  ],
};
